language: go
dist: bionic
go:
  - 1.13.3
services:
  - docker
  - postgresql
env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
addons:
  postgresql: "11"
before_install:
  # Requirement for 'test-local-deployment'
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - psql -c "CREATE DATABASE vulndb_test;" -U postgres
  - psql -c "CREATE USER vulndb_test WITH PASSWORD 'vulndb_test';" -U postgres
  - psql -c "ALTER USER vulndb_test WITH SUPERUSER;" -U postgres
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulnerability-db
script:
  - go install ./...
  - go test -v -tags integration $(go list ./... | grep -v /vendor/) ./test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
  - cd local_deployment
  - ./test-local-deployment.sh
