language: go
dist: trusty
go:
  - 1.13.3
services:
  - postgresql
  - docker
env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE vulndb_test;" -U postgres
  - psql -c "CREATE USER vulndb_test WITH PASSWORD 'vulndb_test';" -U postgres
  - psql -c "ALTER USER vulndb_test WITH SUPERUSER;" -U postgres
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulnerability-db
script:
  - go install ./...
  - go test -v -tags integration $(go list ./... | grep -v /vendor/) ./test
  - cd cmd/vulnerability-db-consumer && go build && cd -
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
