language: go
dist: bionic
go:
  - 1.18.x
services:
  - docker
env:
  global:
    - CGO_ENABLED=0
    - FLYWAY_VERSION=8.5.11
    - INPUT_BUILDARGS=FLYWAY_VERSION=$FLYWAY_VERSION
before_install:
  # Requirement for 'test-local-deployment'
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - _script/start-pg
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulnerability-db
script:
  - go install ./...
  - go test -v -tags integration $(go list ./... | grep -v /vendor/) ./test
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
  - cd local_deployment
  - ./test-local-deployment.sh
