# Defines the max age, in days an event can have to be considered. Events
# older than this age are discarded. If 0 no events are discarded.
max_event_age = $MAX_EVENT_AGE
[log]
# log levels: panic, fatal, error, warn, info, debug, trace
level ="$LOG_LEVEL"

[db]
dialect = "postgres"
host = "$PG_HOST"
port = "$PG_PORT"
user = "$PG_USER"
password = "$PG_PASSWORD"
sslmode = "$PG_SSLMODE"
name = "$PG_NAME"

[sqs]
number_of_processors = 25
wait_time = 20
timeout = 30
queue_arn = "$SQS_QUEUE_ARN"

[sns]
topic_arn = "$SNS_TOPIC_ARN"
enabled = true

[report]
url_replace = "$RESULTS_URL|$RESULTS_INTERNAL_URL"

[maintenance]
# periodical tasks executed in background
# - name: Custom task name
# - type: Task type
# - rate: Time (hours) after which the task will be periodically executed
# - options: Custom option params for each type
#
# available task types:
#  - expire_findings { ttl: Expire time in days, source: findings source name }
#
tasks = [
    {name = "expire_vulcan_findings", type = "expire_findings", rate = 24, options = { ttl=60, source="vulcan" }}
]
