version: '3.7'
services:
  mocked_vulcan_results:
    build: ./mocked_vulcan_results
    command: localroast /reports.json
    ports:
        - 8080:8080

  mocked_database:
    image: postgres:10.9
    ports:
      - 5440:5432
    env_file:
      - ./mocked_database/config.env

  mocked_sns_sqs:
    image: pafortin/goaws:v0.3.1
    ports:
      - 4100:4100
    volumes:
      - ./mocked_sns_sqs:/conf

  flyway:
    image: flyway/flyway:7.8.2
    depends_on: 
      - mocked_database
    volumes:
        - ../db/sql:/app/sql
    command: -user=vulndb -password=vulndb -url=jdbc:postgresql://mocked_database:5432/vulndb?sslmode=disable -connectRetries=60 -baselineOnMigrate=true -locations=filesystem:/app/sql migrate
