# Copyright 2020 Adevinta

version: "2"

services:
    vulndb:
        container_name: vulndb
        image: postgres:10.9
        command: "postgres -c log_connections=true -c log_min_duration_statement=0"
        ports:
            - "5438:5432"
        expose:
            - "5432"
        volumes:
            - /var/lib/postgresql/data
        environment:
            - POSTGRES_USER=vulndb
            - POSTGRES_PASSWORD=vulndb
            - POSTGRES_DB=vulndb
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
            - "8000:80"
            - "8443:443"
        links:
            - vulndb
        environment:
            - PGADMIN_DEFAULT_EMAIL=vulndb@localhost
            - PGADMIN_DEFAULT_PASSWORD=vulndb
